// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teachzilla.Model;

#nullable disable

namespace Teachzilla.Model.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("Teachzilla.Model.Homework", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Due")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.ToTable("Homework", (string)null);
                });

            modelBuilder.Entity("Teachzilla.Model.Lesson", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LessonDate")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentID")
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("StudentID");

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("Teachzilla.Model.Note", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("HomeworkID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LessonID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StudentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("HomeworkID");

                    b.HasIndex("LessonID");

                    b.HasIndex("StudentID");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("Teachzilla.Model.Student", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Updated")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Teachzilla.Model.Homework", b =>
                {
                    b.HasOne("Teachzilla.Model.Student", "Student")
                        .WithMany("Homework")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Teachzilla.Model.Lesson", b =>
                {
                    b.HasOne("Teachzilla.Model.Student", "Student")
                        .WithMany("Lessons")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Teachzilla.Model.Note", b =>
                {
                    b.HasOne("Teachzilla.Model.Homework", "Homework")
                        .WithMany("Notes")
                        .HasForeignKey("HomeworkID");

                    b.HasOne("Teachzilla.Model.Lesson", "Lesson")
                        .WithMany("Notes")
                        .HasForeignKey("LessonID");

                    b.HasOne("Teachzilla.Model.Student", "Student")
                        .WithMany("Notes")
                        .HasForeignKey("StudentID");

                    b.Navigation("Homework");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Teachzilla.Model.Homework", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Teachzilla.Model.Lesson", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Teachzilla.Model.Student", b =>
                {
                    b.Navigation("Homework");

                    b.Navigation("Lessons");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
